name: Deploy to Windows Server 2019

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via PowerShell
      shell: pwsh
      run: |
        $secpasswd = ConvertTo-SecureString '${{ secrets.WS_PASSWORD }}' -AsPlainText -Force
        $cred = New-Object System.Management.Automation.PSCredential ('${{ secrets.WS_USER }}', $secpasswd)
        Invoke-Command -ComputerName '${{ secrets.WS_HOST }}' -Port 5986 -Credential $cred -Authentication Basic -UseSSL -ScriptBlock {
          Write-Host 'Conexion exitosa'
          cd 'C:\PruebasJason'
          git pull
        }
        Write-Host "PRUEBA SERVIDOR"
