name: Deploy to Windows Server 2019

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.WS_USER }}@${{ secrets.WS_HOST }} -p 22 
        "echo 'Conexion establecida';
        cd C:\PruebasJason && git pull"
