name: Deploy to Windows Server 2019

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via Web Deploy
      run: |
        & "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" `
        -verb:sync `
        -source:contentPath="${{ github.workspace }}" `
        -dest:contentPath="Default Web Site",computerName="https://${{ secrets.WS_HOST }}:8172/msdeploy.axd",
        userName="${{ secrets.WS_USER }}",password="${{ secrets.WS_PASSWORD }}",authType="Basic"
